### PR TITLE
Feature/materials as polygroups

### PR DESCRIPTION
**Pull request by kromar**
added a option to transfer materials as polygroups from blender to zbrush

Screen Shot 07-17-19 at 10 24 PM

image

### CODE REVIEW

**Comment by JoseConseco** [comment]
Material from polygroups look cool. 
I'm not sure about shading being preference switch. IMO, we could remove it and just check:
- if already imported objA.data.faces[0].smooth, then shade smoooth whole incoming objA too, else shade flat. This way incoming updated object will gest shading from existing obj already imported previously.
What do you think?

**Comment by kromar** [comment]
i want to add an other option to make polygroups from uv islands but that turns out to be a bit more complicated so i made a new branch for it. thats why i have the preference dropdown.

i dont think i understand what you mean with the shading. do you want to add a option to use smooth groups as polygroups? or is this related to the other pullrequest with the shading fix??

**Comment by JoseConseco** [comment]
"want to add an other option to make polygroups from uv islands " -  there is already option for that in zbrush - polygroups from uvs.

**Comment by kromar** [comment]
that is true, in that case it probably doesnt make much sense to have it in blender as well since its a 1 button operation in zbrush.
if there will be no additional options for the drop down i will change it to a checkbox.

**Comment by kromar** [comment]
@JoseConseco  this one is also not merged^^

**Pull request merged**
