### PR TITLE
Feature/redesign data import

### PR DESCRIPTION
**Pull request by kromar**
This includes a lot of refactoring to support new features like facemaps and so on without going through vertex groups.

check the project for all the changes:
https://github.com/JoseConseco/GoB/projects/1#column-7005111

### CODE REVIEW

**Comment by kromar** [comment]
@JoseConseco i know that is not the way PR's should be done but this change to not need to import data view vertex groups has brought up a lot of issues and needed changes in almost all parts. I also wanted to fix some long outstanding issues and some performance issues thats why this got to a very big diff.

I had some great assistance with testing so im quite confident that this is functionaly stable. I know you do not have much time so i hope you are ok with bringing this back to the main branch.

oh and there are also some more options exposed for the users to customize.
image

i hope you like the new version. 
cheers Daniel

**Comment by Tsukasa-YAMATO** [comment]
Dear Daniel.
Thank you for the bug fix in the past few beta versions. There may have been a lot of hard work, and I think you did well so much.
I've been testing the GoB Ver.3.3.7 Beta version for the past few days, and I haven't found any noticeable issues.

Hi Mr. Jose,
I'm Tsukasa YAMATO. I have provided Mr. Daniel with many suggestions for improvement and beta test results. I'm very pleased to be using a stable beta version now.

Mr. Daniel worked very well. The GoB plugin is now a very important bridging tool for users of Blender and Zbrush. Especially after Ver.3.2.5 is exactlly being massive powerful tool. I assure it.

 If there is no problem, I would like you to publish it as a stable version. Many users want it.

Thank you for developing GoB addon.

Best regards,
Tsukasa YAMATO

**Comment by JoseConseco** [comment]
All right, I may look into code later this week, but if it was tested and it stable than its fine for me. Thanks for taking care of the addon @kromar .

**Comment by kromar** [comment]
@JoseConseco thanks for the approval! sure looking forward to your feedback on the code.
I will start putting toghether the release notes, so we can do a nice release.

@Tsukasa-YAMATO thanks again for all the testing,the help finding and eliminating all the bugs and your kind words. You made my work so much easier!

**Pull request merged**
