### PR TITLE
Feature/rebaseonmaster

### PR DESCRIPTION
**Pull request by kromar**
i rebased the 2.8 branch on the latest master and updated it with all the changes that i made on the 2.7 version. so it should be relatively easy to bring changes on the master forward to the 2.8 branch.

- linked objects will create a copy for now (later on we might introduce a option to update the linked object but i think its not possible yet).
- i added a "fix" for the triangulation but its a bit nasty but at least will not crash zbrush .
- the updater is added as well and i needed to bump the version so we dont get conflicts with the 2.7 version.
- i also added the custom icons but there seems to be some issue in blender so the icons are not drawn, so its disabled for the moment. i will file a bug report and we can enable them once its working.

also there is some bug when importing the files from zbrush, i added a bit more output for the tags but since i do not have the SDK i dont really know what the file is containing. do you have the SDK?
maybe something in the parsing is wrong since the tag that is reporteed looks really similar to the polygroups tag (or maybe its a tag for empty polygroups?)

`Importing: ('C:/Users/Public/Pixologic/GoZProjects/Default/Cube.GoZ', 'Cube')
tags:  b'\x89\x13\x00\x00'
tags:  b"\x11'\x00\x00"
tags:  b'!N\x00\x00'
tags:  b'\xa9a\x00\x00'
**unknown tag:b'B\x9c\x00\x00'**
try to skip it...
Info: Done`

### CODE REVIEW

**Comment by JoseConseco** [comment]
I dont have the sdk. I dont know what those other tags do.
- zbrush has problems with . in object name (you cant edit '.' in zbrush subtool name) . Maybe we should escape it too...
- the triangulate could be problematic of heavy meshes. Not sure how bad it may be. And subsurface modfier gets rid of ngons automatically, so maybe GOB should detect subsurface exist. On left ngon with subsurface. On right ngon, converted to tri (then merge tris) then subsurface
image
- since 2.8 port, addon lost ability to export diff, normal, color maps.  Maye you want to add it back?
The old code uses - exslot.texture.type - but it was used only in blender internal materials. Now it is no longer supported , since every material is node based.
Nice job with the autoupdater.

**Comment by kromar** [comment]
> since 2.8 port, addon lost ability to export diff, normal, color maps. Maye you want to add it back?

was that lost with this merge? or hass this not been updated to 2.8 yet?

**Comment by kromar** [comment]
hm i thought there was already someething that replaced the . with _ if not then we should think about the best way to make this work since zbrush also needs to send these meshes back and potentially needs to convert to object names with the '.'

with the triangulation i would wait a bit before adding more scenarios. there is a different behaviour to earlier versions and might be fixed before the official release. the current triangulation is in place to avoid crashing zbrush and should be a temporary solution.
however i see the issue with the subsurface. i can add that to the existing triangulation check.

**Comment by JoseConseco** [comment]
> was that lost with this merge? or hass this not been updated to 2.8 yet?

Nope. I just commented out lines after 580.
`for texslot in GoBmat.material.texture_slots:`
Because I do not use textures too much between zbrush and blender. But maybe you want to look into  bringing back this feature. 

About naming - imo GOB should change name of object:  Cube.001  -> to Cube_001. So that bringing back Cube_001 from zbrush to blender will update corrent original mesh original. That is why in escape_object_name() function, I made change to rename object name. Removing '.' is just matter of changing regex.

About triangulation - it should be done after all other modifiers IMO. For example imagine user uses booleans, the source meshes may be all quad, but boolean result  may consist of ngons.  There may be other cases like that.

**Comment by kromar** [comment]
i also do not use textures, so maybe something to tackle later down the road.

ah yes i see now that if the name contains a '.' it will be striped down and end up in zbrush without the ending. i will see that i can add that to the linked object copy.
the issue i see here is that users might want to name their objects with a '.' and we need to change that or store a reference object to that to do the proper exchange:/
EDIT: it seems the rename function is **not working in the 2.8** , i tested in 2.7 and its working there.

I agree, it should be done after the other modifiers, i will change that.

**Pull request merged**
