### PR TITLE
Bugfix/fix shading

### PR DESCRIPTION
**Pull request by kromar**
i fixed a issue where normals were not udpated after the mesh transformations (axis flips)

Screen Shot 07-08-19 at 10 27 PM

and also added a option so the users can choose wether the meshes should be imported smooth or flat shaded.

image

### CODE REVIEW

**Comment by kromar** [comment]
i think your question was for this pullrequest:

`I'm not sure about shading being preference switch. IMO, we could remove it and just check:

if already imported objA.data.faces[0].smooth, then shade smoooth whole incoming objA too, else shade flat. This way incoming updated object will gest shading from existing obj already imported previously.
What do you think?`

sounds like it could work, i will need to test this and see how it behaves. I currently have not so much time so maybe you want to try it.

**Comment by JoseConseco** [comment]
Maybe later. It is small thing

**Comment by kromar** [comment]
did you intend to close the PR's without merging?

**Comment by JoseConseco** [comment]
Ah, thanks for info. I thout closing it will merge the pull request automatically

**Pull request merged**
