### PR TITLE
Feature/switch modifier stack

### PR DESCRIPTION
**Pull request by kromar**
rebased after last merge

### CODE REVIEW

**Comment by kromar** [comment]
oh i seen you did something more efficient with the triangulation; i noticed that the custom icons started to work so i ninja committed them to this PR

**Comment by JoseConseco** [comment]
I was doiing lots of refactoring on GOZ. Now it is using timers, instead of modal operator. I enabled icons too. So this pull request is not longer requiered.  BTW. can i remove the branches:
image
 Are you are working on them, or they are just created when creating pull request?
I'm going to do release 3.0.2 now. Unless you spot some bugs.

**Comment by JoseConseco** [comment]
Btw sorry, but I had to remove the object mode_set. There is bug / missing feature in blender that causes mode_set.poll () to fail when called from timers.
https://developer.blender.org/T62074

**Comment by kromar** [comment]
yeah sure go ahead and delete them, i usually keep them on my fork until they are merged and i do not work on those anymore.
where do we use the object_mode set? was this for the edit mode workaround?

**Comment by JoseConseco** [comment]
Yes, but I had to change it becaouse of timers, and  bad poll, and context override. Complex stuff. So I simplified it jut to leave editmode before importing goz files.

**Comment by kromar** [comment]
btw i was adding a vertex color node yesterday so the color from zbrush is represented in blender when gozing it. i want to give it a couple of tests to catch the scenarios where it does not work but i think it would be a good step before reintroducing the texture system.
heres the branch if you want to have a look:
https://github.com/kromar/blender_GoB/tree/feature/material_import

**Comment by kromar** [comment]
ok thats fine with me, as long as it does not crash or throw errors when in edit mode then its fine^^

**Pull request closed without merging**
